# Generated by Django 5.1.7 on 2025-03-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=5)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('no_of_guests', models.IntegerField(verbose_name=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name=5)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.IntegerField(verbose_name=5)),
            ],
        ),
    ]
